server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/animals_lang
    username: postgres
    password: 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update

swagger:
  access:
    login: swagger
    password: swaggerPass